@startuml
'https://plantuml.com/class-diagram

package "MicroServicios" {
    class GestionAguaWakanda{}
}

package "Sensores"{
    class SensorAgua{}
}

package "FrontEnd"{
    class FrontEnd{}
}


GestionAguaWakanda --> SensorAgua

SensorAgua --> FrontEnd


@enduml